canvas = document.getElementById("canvas")
context = canvas.getContext('2d')
chart = new Chart(canvas, context)
chart.setRectMargin(10)
chart.setVerticalPeriod(0, 100, 3)
chart.setHorizontalPeriod(0, 100, 3)
chart.drawRectList('black')
// chart.setRectColor(1, '#09F')
chart.setRectContent(1, '#09F', 'ID 1', {'color':'#FFF', 'type':'Courier', 'size':'20px'})
chart.setRectContent(2, '#09F', 'ID 2', {'color':'#FFF', 'type':'Courier', 'size':'20px'})
chart.setRectContent(3, '#09F', Math.round(context.measureText('Gabriel').width) + 'px', {'color':'#FFF', 'type':'Courier', 'size':'20px'})
chart.setPersistentFont('Courier', 20, '#FFF', 20, 5)
chart.drawTextOnRect(5, 'Ola[%]Mundo!')